# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='city',
            new_name='city_name',
        ),
    ]
