# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20170209_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=300)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
