# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='city',
        ),
    ]
